// ADR-0016 W1 — flagship store-contribution example tests (CrazyGames).
//
// Mirrors the former Yandex Games pilot tests: phase ordering through the
// generate emitter's exact output, the requiredSdkGlobal seam (surfaced in
// describeLines — ADR-0016 W1), the inject-emitter migration path
// (byte-identical outside the markers), actionable marker failures, a
// valid target chain, and the drift-gate cleanliness of the example.
//
// The Yandex Games contribution now lives in the migrating app's own repo
// (adopted via the inject emitter); CrazyGames is the in-repo flagship.
import 'dart:io';

import 'package:oka_core/oka_core.dart';
import 'package:oka_web/oka_web.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../example/crazygames/compose_example.dart';
import '../example/crazygames/crazygames_contribution.dart';

/// The composed store shell under test.
const WebShell _shell = WebShell(
  spec: crazyGamesSpec,
  contributions: [crazyGames],
);

/// A hand-maintained `web/index.html` fixture resembling a legacy store
/// branch: hand-written head, the FROZEN old Flutter template
/// (`flutter.js` + a pinned `serviceWorkerVersion`), and a loading
/// container — plus the oka markers the migration adds once.
const String _legacyCrazyGamesHtml = r'''
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root of the
    server, change the href value below to reflect the base path.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A word learning game.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="word_by_word_game">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- custom analytics: hand-maintained, must survive emission -->
  <!-- <script src="https://example.test/analytics.js"></script> -->

  <title>word_by_word_game</title>
  <link rel="manifest" href="manifest.json">
  <!-- oka:begin:head -->
  <!-- oka:end:head -->
</head>
<body>
  <!-- oka:begin:body -->
  <!-- oka:end:body -->
  <div id="loading">Загрузка…</div>
  <script src="flutter.js"></script>
  <script>
    window.addEventListener('load', function (ev) {
      _flutter.loader.loadEntrypoint({
        serviceWorker: { serviceWorkerVersion: '3956417298' },
      }).then(function (engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function (appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
</html>
''';

WebScriptEntry? _script(final WebShell shell, final String? src) {
  for (final entry in shell.head) {
    if (entry is WebScriptEntry && entry.src == src) return entry;
  }
  return null;
}

void main() {
  group('phase ordering (through the generate emitter)', () {
    test('renders index.html exactly: preconnect BEFORE the SDK script',
        () {
      final output = const GenerateShellEmitter().emit(_shell);
      expect(output.files.keys, ['index.html', 'manifest.json']);
      expect(output.files['index.html'], '''
<!DOCTYPE html>
<html>
<head>
  <!--
    Generated by oka (oka_web `generate` emitter, ADR-0016). Do not edit — recompose the shell instead; this file is owned by oka.
  -->
  <base href="/">
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="Learn words by playing. Word by word.">
  <!-- oka: iOS meta tags & icons -->
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Word by Word — CrazyGames">
  <title>Word by Word — CrazyGames</title>
  <link rel="manifest" href="manifest.json">
  <!-- oka: composed shell entries (preconnect → storeSdk → app) -->
  <link rel="preconnect" href="https://sdk.crazygames.com/">
  <script src="https://sdk.crazygames.com/crazygames-sdk-v3.js"></script>
</head>
<body>
  <script src="flutter_bootstrap.js" async></script>
</body>
</html>
''');
    });

    test('storeSdk entries sort before every app entry in shell.head', () {
      final head = _shell.head;
      final sdkIndex =
          head.indexWhere((final e) => e.phase == WebHeadPhase.storeSdk);
      final firstAppIndex =
          head.indexWhere((final e) => e.phase == WebHeadPhase.app);
      expect(sdkIndex, greaterThanOrEqualTo(0));
      if (firstAppIndex >= 0) expect(firstAppIndex, greaterThan(sdkIndex));
    });
  });

  group('requiredSdkGlobal seam', () {
    test('the SDK entry carries CrazyGames for doctor/gate reconciliation',
        () {
      final sdk = _script(_shell, CrazyGamesShellContribution.sdkUrl);
      expect(sdk, isNotNull);
      expect(sdk!.requiredSdkGlobal, 'CrazyGames');
      expect(sdk.phase, WebHeadPhase.storeSdk);
    });

    test('describeLines surfaces requiredSdkGlobal per entry (ADR-0016 W1)',
        () {
      final lines = _shell.describeLines();
      final entryLine = lines
          .firstWhere((final l) => l.contains('crazygames-sdk-v3.js'));
      expect(
        entryLine,
        contains('requiredSdkGlobal=CrazyGames'),
        reason: 'the SDK-global declaration must be visible to '
            '`oka explain --targets` (real-world W1 feedback)',
      );
      expect(entryLine, contains('storeSdk'));
    });

    test('entry toString() carries requiredSdkGlobal; entries without one '
        'stay unchanged', () {
      const withGlobal = WebScriptEntry(
        src: 'https://x.test/sdk.js',
        phase: WebHeadPhase.storeSdk,
        requiredSdkGlobal: 'X',
      );
      const without = WebScriptEntry(src: 'https://x.test/app.js');
      expect(withGlobal.toString(), contains('requiredSdkGlobal=X'));
      expect(without.toString(), isNot(contains('requiredSdkGlobal')));
    });
  });

  group('inject emitter — the legacy migration path', () {
    test('adds ONLY the contribution entries between the markers; the rest '
        'is byte-identical', () {
      final output = const InjectShellEmitter()
          .emit(_shell, existingIndexHtml: _legacyCrazyGamesHtml);
      expect(output.files.keys, ['index.html']);
      expect(output.files['index.html'], r'''
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root of the
    server, change the href value below to reflect the base path.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A word learning game.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="word_by_word_game">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- custom analytics: hand-maintained, must survive emission -->
  <!-- <script src="https://example.test/analytics.js"></script> -->

  <title>word_by_word_game</title>
  <link rel="manifest" href="manifest.json">
  <!-- oka:begin:head -->
  <link rel="preconnect" href="https://sdk.crazygames.com/">
  <script src="https://sdk.crazygames.com/crazygames-sdk-v3.js"></script>
  <!-- oka:end:head -->
</head>
<body>
  <!-- oka:begin:body -->
  <!-- oka:end:body -->
  <div id="loading">Загрузка…</div>
  <script src="flutter.js"></script>
  <script>
    window.addEventListener('load', function (ev) {
      _flutter.loader.loadEntrypoint({
        serviceWorker: { serviceWorkerVersion: '3956417298' },
      }).then(function (engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function (appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
</html>
''');
      // The frozen template block must survive untouched — the branch's
      // reason for existence (pinning it) is irrelevant under oka.
      expect(
        output.files['index.html'],
        contains("serviceWorkerVersion: '3956417298'"),
      );
      // SSOT split caveat (real-world W1 feedback): the hand-maintained
      // title/description stay — injection owns head/body ENTRIES only,
      // not the spec identity fields rendered by the generate emitter.
      expect(output.files['index.html'], contains('A word learning game.'));
      expect(
        output.files['index.html'],
        isNot(contains(crazyGamesSpec.description)),
      );
    });

    test('re-injection is idempotent (marker regions match the composition '
        'after the first run)', () {
      final first = const InjectShellEmitter()
          .emit(_shell, existingIndexHtml: _legacyCrazyGamesHtml)
          .files['index.html']!;
      final second = const InjectShellEmitter()
          .emit(_shell, existingIndexHtml: first)
          .files['index.html']!;
      expect(second, first);
    });

    test('missing markers fail with an actionable message', () {
      final withoutMarkers = _legacyCrazyGamesHtml
          .replaceFirst('  <!-- oka:begin:head -->\n', '')
          .replaceFirst('  <!-- oka:end:head -->\n', '');
      expect(
        () => const InjectShellEmitter()
            .emit(_shell, existingIndexHtml: withoutMarkers),
        throwsA(
          isA<ShellInjectionException>().having(
            (final e) => e.message,
            'message',
            allOf([
              contains('no head markers'),
              contains('<!-- oka:begin:head -->'),
              contains('<!-- oka:end:head -->'),
              contains('never rewrites regions outside the markers'),
            ]),
          ),
        ),
      );
    });

    test('quote-style caveat (real-world W1 feedback): emitted inline '
        'entries render inline scripts with single quotes where a legacy '
        'hand-written file may use double quotes — byte-compare against '
        'legacy files does not match exactly; injection owns the region '
        'instead', () {
      // The composition's inline entries are declarative renders; the
      // emitter never tries to imitate legacy quote style.
      final output = const GenerateShellEmitter().emit(_shell);
      expect(
        output.files['index.html'],
        contains(
          '<script src="${CrazyGamesShellContribution.sdkUrl}"></script>',
        ),
      );
    });
  });

  group('target chain', () {
    late Directory temp;

    setUp(() => temp = Directory.systemTemp.createTempSync('oka_web_w1_'));
    tearDown(() => temp.deleteSync(recursive: true));

    test('validate step passes for the composed store shell', () async {
      final ctx = BuildContext(
        projectPath: temp.path,
        buildDir: p.join(temp.path, '.oka', 'build'),
        mode: BuildMode.release,
        config: OkaConfig.empty,
      );
      final pipeline = Pipeline([
        ...crazyGamesGenerateShell.compile(ctx),
      ]);
      expect(pipeline.validate(), isNull);
      final result = await pipeline.run(ctx);
      expect(result.ok, isTrue, reason: result.error ?? '');
      expect(
        File(p.join(temp.path, 'web', 'index.html')).readAsStringSync(),
        contains('crazygames-sdk-v3.js'),
      );
    });

    test('the composed store shell has no pure validation issues', () {
      expect(shellIssues(_shell), isEmpty);
    });

    test('duplicate composition is rejected by identity keys (no hidden '
        'merging, ADR-0010)', () {
      const doubled = WebShell(
        spec: crazyGamesSpec,
        contributions: [crazyGames, crazyGames],
      );
      final issues = shellIssues(doubled);
      expect(issues, isNotEmpty);
      expect(issues.join('\n'), contains('duplicate head entry'));
    });

    test('WebShellTarget.explainDetails carries the composition render '
        '(pure, no I/O)', () {
      const ctx = BuildContext(
        projectPath: '.',
        buildDir: '.oka/build',
        mode: BuildMode.debug,
        config: OkaConfig.empty,
      );
      final details = crazyGamesGenerateShell.explainDetails(ctx);
      expect(details.join('\n'), allOf(
        contains('shell: "Word by Word — CrazyGames"'),
        contains('requiredSdkGlobal=CrazyGames'),
      ));
    });
  });

  group('manifest decision', () {
    test('contribution declares no manifest override (documented decision)',
        () {
      expect(crazyGames.manifest, isNull);
      // The composed manifest falls back to the spec identity fields.
      expect(_shell.manifest.name, crazyGamesSpec.title);
      expect(_shell.manifest.display, crazyGamesSpec.display);
    });
  });
}
