// ADR-0016 W0 — GenerateShellEmitter exact-output tests.
//
// The generate emitter owns `web/index.html` + `web/manifest.json`; these
// tests pin the exact rendered bytes (pure string builders, no I/O) and
// decode the manifest JSON to assert field correctness.
import 'dart:convert';

import 'package:oka_web/oka_web.dart';
import 'package:test/test.dart';

const _spec = WebShellSpec(
  title: 'Example',
  description: 'An example web app.',
  baseHref: '/',
  themeColor: '#0175C2',
  backgroundColor: '#FFFFFF',
  display: 'standalone',
  orientation: 'portrait-primary',
  startUrl: '.',
  icons: WebIconSpec(
    icon192: 'icons/Icon-192.png',
    icon512: 'icons/Icon-512.png',
    maskable: 'icons/Icon-maskable-512.png',
    favicon: 'favicon.png',
  ),
  metaEntries: [
    WebMetaEntry(
      name: 'viewport',
      content: 'width=device-width, initial-scale=1',
    ),
  ],
);

const _yaGames = SimpleWebShellContribution(
  head: [
    WebLinkEntry(
      rel: 'preconnect',
      href: 'https://sdk.games.s3.yandex.net',
      crossOrigin: 'anonymous',
      phase: WebHeadPhase.preconnect,
    ),
    WebScriptEntry(
      src: 'https://yandex.ru/games/sdk/v2',
      phase: WebHeadPhase.storeSdk,
      requiredSdkGlobal: 'YaGames',
    ),
  ],
  body: [WebElementEntry(tag: 'div', id: 'loading')],
);

WebShell composedShell() =>
    WebShell(spec: _spec, contributions: const [_yaGames]);

void main() {
  test('renders index.html exactly (Flutter stable template shape)', () {
    const emitter = GenerateShellEmitter();
    final output = emitter.emit(composedShell());
    expect(output.files.keys, ['index.html', 'manifest.json']);
    expect(output.files['index.html'], '''
<!DOCTYPE html>
<html>
<head>
  <!--
    Generated by oka (oka_web `generate` emitter, ADR-0016). Do not edit — recompose the shell instead; this file is owned by oka.
  -->
  <base href="/">
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="An example web app.">
  <meta name="theme-color" content="#0175C2">
  <!-- oka: iOS meta tags & icons -->
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Example">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">
  <!-- oka: favicon -->
  <link rel="icon" type="image/png" href="favicon.png">
  <title>Example</title>
  <link rel="manifest" href="manifest.json">
  <!-- oka: composed shell entries (preconnect → storeSdk → app) -->
  <link rel="preconnect" href="https://sdk.games.s3.yandex.net" crossorigin="anonymous">
  <script src="https://yandex.ru/games/sdk/v2"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <!-- oka: composed body entries -->
  <div id="loading"></div>
  <script src="flutter_bootstrap.js" async></script>
</body>
</html>
''');
  });

  test('renders manifest.json exactly', () {
    const emitter = GenerateShellEmitter();
    final output = emitter.emit(composedShell());
    expect(output.files['manifest.json'], '''
<!--
  Generated by oka (oka_web `generate` emitter, ADR-0016). Do not edit — recompose the shell instead; this file is owned by oka.
-->
{
    "name": "Example",
    "short_name": "Example",
    "start_url": ".",
    "display": "standalone",
    "theme_color": "#0175C2",
    "background_color": "#FFFFFF",
    "description": "An example web app.",
    "orientation": "portrait-primary",
    "prefer_related_applications": false,
    "icons": [
        {
            "src": "icons/Icon-192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "icons/Icon-512.png",
            "sizes": "512x512",
            "type": "image/png"
        },
        {
            "src": "icons/Icon-maskable-512.png",
            "sizes": "512x512",
            "type": "image/png",
            "purpose": "maskable"
        }
    ]
}
''');
  });

  test('manifest JSON decodes with the composed field values', () {
    const emitter = GenerateShellEmitter();
    final output = emitter.emit(composedShell());
    final banner = RegExp(r'^<!--[\s\S]*?-->\n');
    final json =
        jsonDecode(output.files['manifest.json']!.replaceFirst(banner, ''))
            as Map<String, dynamic>;
    expect(json['name'], 'Example');
    expect(json['short_name'], 'Example');
    expect(json['start_url'], '.');
    expect(json['display'], 'standalone');
    expect(json['theme_color'], '#0175C2');
    expect(json['background_color'], '#FFFFFF');
    expect(json['description'], 'An example web app.');
    expect(json['orientation'], 'portrait-primary');
    expect(json['prefer_related_applications'], false);
    expect(json['icons'], [
      {
        'src': 'icons/Icon-192.png',
        'sizes': '192x192',
        'type': 'image/png',
      },
      {
        'src': 'icons/Icon-512.png',
        'sizes': '512x512',
        'type': 'image/png',
      },
      {
        'src': 'icons/Icon-maskable-512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'maskable',
      },
    ]);
  });

  test('manifest overrides from contributions apply (last wins)', () {
    const storeOverride = SimpleWebShellContribution(
      manifest: PwaManifestOverride(
        display: 'fullscreen',
        orientation: 'landscape',
        shortName: 'YaGame',
      ),
    );
    final shell = WebShell(
      spec: _spec,
      contributions: const [_yaGames, storeOverride],
    );
    final manifest = shell.manifest;
    expect(manifest.display, 'fullscreen');
    expect(manifest.orientation, 'landscape');
    expect(manifest.shortName, 'YaGame');
    // Un-overridden fields keep spec values.
    expect(manifest.name, 'Example');
    expect(manifest.themeColor, '#0175C2');
  });

  test('empty description/colors omit the corresponding tags and keys', () {
    const minimal = WebShellSpec(title: 'Tiny');
    final output = const GenerateShellEmitter()
        .emit(WebShell(spec: minimal, contributions: const []));
    final html = output.files['index.html']!;
    expect(html, isNot(contains('name="description"')));
    expect(html, isNot(contains('theme-color')));
    expect(html, isNot(contains('apple-touch-icon')));
    expect(html, isNot(contains('favicon')));
    expect(html, contains('<title>Tiny</title>'));
    final json = jsonDecode(
      output.files['manifest.json']!.replaceFirst(
        RegExp(r'^<!--[\s\S]*?-->\n'),
        '',
      ),
    ) as Map<String, dynamic>;
    expect(json.containsKey('theme_color'), isFalse);
    expect(json.containsKey('background_color'), isFalse);
    expect(json['name'], 'Tiny');
    expect(json['icons'], isEmpty);
  });

  test('escapes attribute values and text content', () {
    const shell = WebShell(
      spec: WebShellSpec(
        title: 'A & "B" <C>',
        baseHref: '/app/',
        metaEntries: [
          WebMetaEntry(name: 'x"q', content: 'a&b<c>"d"'),
        ],
      ),
    );
    final html =
        const GenerateShellEmitter().emit(shell).files['index.html']!;
    expect(html, contains('<meta name="x&quot;q" content="a&amp;b&lt;c&gt;&quot;d&quot;">'));
    expect(html, contains('<title>A &amp; &quot;B&quot; &lt;C&gt;</title>'));
    expect(html, contains('<base href="/app/">'));
  });

  test('emit replaces an existing index.html and says so in notes', () {
    final output = const GenerateShellEmitter().emit(
      composedShell(),
      existingIndexHtml: '<!-- hand-tuned legacy -->',
    );
    expect(output.notes, [
      'generate: existing index.html is REPLACED (this emitter owns it)',
    ]);
  });

  test('ownedPaths are exactly the two generated files', () {
    expect(const GenerateShellEmitter().ownedPaths,
        {'index.html', 'manifest.json'});
    expect(const GenerateShellEmitter().name, 'generate');
  });
}
