/// The default generate emitter (ADR-0016 §1): oka owns `web/index.html` +
/// `web/manifest.json`.
///
/// Pure string builders — no I/O — so unit tests assert exact output. The
/// Flutter template coupling (flutter_bootstrap.js shape) is contained in
/// this one class.
library;

import 'dart:convert';

import 'package:meta/meta.dart';

import '../composition.dart';
import '../emitter.dart';
import 'render.dart';
/// Generated-content banner written into every owned file.
const String generatedBanner =
    'Generated by oka (oka_web `generate` emitter, ADR-0016). Do not edit — '
    'recompose the shell instead; this file is owned by oka.';

/// The default emitter: renders the full shell from the composition.
///
/// Owns `web/index.html` and `web/manifest.json` (declared in
/// [ownedPaths] for the W1 drift gate). Template shape follows the current
/// stable Flutter web template (`flutter_bootstrap.js`).
@immutable
class GenerateShellEmitter extends ShellEmitter {
  /// Const constructor — ships as `const GenerateShellEmitter()`.
  const GenerateShellEmitter();

  /// Emitter name: `generate`.
  @override
  String get name => 'generate';

  /// Owns the whole `index.html` and `manifest.json` files.
  @override
  Set<String> get ownedPaths => const {'index.html', 'manifest.json'};

  /// Renders both owned files from scratch — [existingIndexHtml] is
  /// ignored (a non-empty one only produces a replacement note).
  @override
  ShellOutput emit(
    final WebShell shell, {
    final String? existingIndexHtml,
  }) {
    final notes = <String>[
      if (existingIndexHtml != null && existingIndexHtml.isNotEmpty)
        'generate: existing index.html is REPLACED (this emitter owns it)',
    ];
    return ShellOutput(
      files: {
        'index.html': renderIndexHtml(shell),
        'manifest.json': renderManifestJson(shell),
      },
      notes: notes,
    );
  }

  /// Renders the full `index.html` (Flutter stable template shape).
  String renderIndexHtml(final WebShell shell) {
    final manifest = shell.manifest;
    final icons = manifest.icons;
    final buffer = StringBuffer()
      ..writeln('<!DOCTYPE html>')
      ..writeln('<html>')
      ..writeln('<head>')
      ..writeln('  <!--')
      ..writeln('    $generatedBanner')
      ..writeln('  -->')
      ..writeln('  <base href="${escapeAttribute(shell.baseHref)}">')
      ..writeln('  <meta charset="${escapeAttribute(shell.spec.charset)}">')
      ..writeln('  <meta content="IE=Edge" http-equiv="X-UA-Compatible">');
    if (manifest.description.isNotEmpty) {
      buffer.writeln(
        '  <meta name="description" '
        'content="${escapeAttribute(manifest.description)}">',
      );
    }
    if (manifest.themeColor.isNotEmpty) {
      buffer.writeln(
        '  <meta name="theme-color" '
        'content="${escapeAttribute(manifest.themeColor)}">',
      );
    }
    if (shell.title.isNotEmpty) {
      buffer
        ..writeln('  <!-- oka: iOS meta tags & icons -->')
        ..writeln('  <meta name="mobile-web-app-capable" content="yes">')
        ..writeln(
          '  <meta name="apple-mobile-web-app-status-bar-style" '
          'content="black">',
        )
        ..writeln(
          '  <meta name="apple-mobile-web-app-title" '
          'content="${escapeAttribute(shell.title)}">',
        );
    }
    if (icons.icon192.isNotEmpty) {
      buffer.writeln(
        '  <link rel="apple-touch-icon" '
        'href="${escapeAttribute(icons.icon192)}">',
      );
    }
    if (icons.favicon.isNotEmpty) {
      buffer
        ..writeln('  <!-- oka: favicon -->')
        ..writeln(
          '  <link rel="icon" type="image/png" '
          'href="${escapeAttribute(icons.favicon)}">',
        );
    }
    if (shell.title.isNotEmpty) buffer.writeln('  <title>${escapeText(shell.title)}</title>');
    buffer
      ..writeln('  <link rel="manifest" href="manifest.json">')
      ..writeln(
        '  <!-- oka: composed shell entries '
        '(preconnect → storeSdk → app) -->',
      );
    for (final entry in shell.head) {
      buffer.writeln(renderHeadEntry(entry));
    }
    buffer.writeln('</head>');
    buffer.writeln('<body>');
    if (shell.body.isNotEmpty) {
      buffer.writeln('  <!-- oka: composed body entries -->');
      for (final entry in shell.body) {
        renderBodyEntry(entry).forEach(buffer.writeln);
      }
    }
    buffer
      ..writeln('  <script src="flutter_bootstrap.js" async></script>')
      ..writeln('</body>')
      ..writeln('</html>');
    return buffer.toString();
  }

  /// Renders `manifest.json` (4-space indent, Flutter template shape).
  String renderManifestJson(final WebShell manifestShell) {
    final manifest = manifestShell.manifest;
    final icons = manifest.icons;
    final manifestIcons = <Map<String, String>>[
      if (icons.icon192.isNotEmpty)
        {'src': icons.icon192, 'sizes': '192x192', 'type': 'image/png'},
      if (icons.icon512.isNotEmpty)
        {'src': icons.icon512, 'sizes': '512x512', 'type': 'image/png'},
      if (icons.maskable.isNotEmpty)
        {
          'src': icons.maskable,
          'sizes': '512x512',
          'type': 'image/png',
          'purpose': 'maskable',
        },
    ];
    final value = <String, Object?>{
      'name': manifest.name,
      'short_name': manifest.shortName,
      'start_url': manifest.startUrl,
      'display': manifest.display,
      if (manifest.themeColor.isNotEmpty) 'theme_color': manifest.themeColor,
      if (manifest.backgroundColor.isNotEmpty)
        'background_color': manifest.backgroundColor,
      if (manifest.description.isNotEmpty)
        'description': manifest.description,
      'orientation': manifest.orientation,
      'prefer_related_applications': manifest.preferRelatedApplications,
      'icons': manifestIcons,
    };
    const encoder = JsonEncoder.withIndent('    ');
    return '''
<!--
  $generatedBanner
-->
${encoder.convert(value)}
''';
  }
}
